# Generated by Django 5.2 on 2025-04-25 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='num_in_quiz',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
