# Generated by Django 5.1.7 on 2025-03-24 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questions',
            old_name='quiz_id',
            new_name='quiz',
        ),
    ]
