# Generated by Django 5.2 on 2025-05-17 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_question_num_in_quiz'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='num_in_quiz',
        ),
    ]
