# Generated by Django 5.2 on 2025-05-17 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20250426_0208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='num_in_quiz',
        ),
        migrations.AlterField(
            model_name='quizresult',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='QuesResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isTrue', models.BooleanField()),
                ('ques', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.question')),
                ('quizRes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.quizresult')),
            ],
        ),
    ]
