# Generated by Django 5.2 on 2025-05-19 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_question_num_in_quiz'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='ques',
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='main.question'),
        ),
    ]
