# Generated by Django 5.1.7 on 2025-03-26 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_answers_answer_rename_questions_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='num_in_quiz',
            field=models.IntegerField(null=True),
        ),
    ]
