# Generated by Django 5.1.7 on 2025-03-29 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_question_num_in_quiz'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(unique=True)),
                ('name', models.CharField()),
                ('surname', models.CharField()),
            ],
        ),
    ]
