# Generated by Django 5.1.7 on 2025-03-30 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_user_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='nickname',
            new_name='username',
        ),
    ]
